### ISSUE TITLE
Copying folder named "projects" over from ialsa-2015-portland

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#10]
This folder had the following folders:
- [x] cognitive
- [x] gait
- [x] github_lables.md
- [x] grip
- [x] manuscript
- [x] physical
- [x] physical-cognnitive
- [x] pulmonary
- [x] README.md
- [x] table_1_descriptive

**Comment by Maleeha** [comment]
Done! @wibeasley

**Comment by wibeasley** [comment]
I don't see a folder called `./projects/`.  Any chance you forgot to sync?

**Comment by Maleeha** [comment]
@wibeasley still working on a few things for it. Please check in to see in half an hour. Thanks

**Comment by wibeasley** [comment]
@Maleeha, sorry for rushing you.  Just close the issue when you're done, and I'll look at it then.

Also, go ahead and correct spelling mistakes (eg, "lables") and change the rename _files_ (not variables) to our new convention (ie, all lowercase with dashes).
